spring.application.name=ticketingsystem

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=IRAWAG_TRN_DB;encrypt=true;trustServerCertificate=true
spring.datasource.username=pocUser
spring.datasource.password=pocUser

#spring.jackson.deserialization.FAIL_ON_NULL_FOR_PRIMITIVES=false